# Generated by Django 6.0.3 on 2026-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up_needed', 'Follow Up Needed'), ('converted', 'Converted')], max_length=30),
        ),
    ]
