# Generated by Django 6.0.3 on 2026-03-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_visit_next_follow_up_date_visit_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.campaign'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up_needed', 'Follow Up Needed'), ('converted', 'Converted')], default='', max_length=30),
        ),
    ]
